// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARjr5vudt9BqYsp3v0D-IUmbYQMDxvwJU',
    appId: '1:327735821612:web:0957543e48d277a128d889',
    messagingSenderId: '327735821612',
    projectId: 'flutter-force-update-service',
    authDomain: 'flutter-force-update-service.firebaseapp.com',
    storageBucket: 'flutter-force-update-service.firebasestorage.app',
    measurementId: 'G-FFZ0HWGY18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDf-DKMbx2QC6b-_h99nW8eoIUKyiA9Seg',
    appId: '1:327735821612:android:680ca42d26b60bbe28d889',
    messagingSenderId: '327735821612',
    projectId: 'flutter-force-update-service',
    storageBucket: 'flutter-force-update-service.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuYlnRCje9fCjkMYYBFKr62xRauiYofrc',
    appId: '1:327735821612:ios:17fb69a1ee6ef4c028d889',
    messagingSenderId: '327735821612',
    projectId: 'flutter-force-update-service',
    storageBucket: 'flutter-force-update-service.firebasestorage.app',
    iosBundleId: 'com.example.flutterForceUpdateService',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuYlnRCje9fCjkMYYBFKr62xRauiYofrc',
    appId: '1:327735821612:ios:17fb69a1ee6ef4c028d889',
    messagingSenderId: '327735821612',
    projectId: 'flutter-force-update-service',
    storageBucket: 'flutter-force-update-service.firebasestorage.app',
    iosBundleId: 'com.example.flutterForceUpdateService',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARjr5vudt9BqYsp3v0D-IUmbYQMDxvwJU',
    appId: '1:327735821612:web:0a692d54d790a53e28d889',
    messagingSenderId: '327735821612',
    projectId: 'flutter-force-update-service',
    authDomain: 'flutter-force-update-service.firebaseapp.com',
    storageBucket: 'flutter-force-update-service.firebasestorage.app',
    measurementId: 'G-X3V4BG9MJK',
  );
}
